You can't call initCause on a ClassNotFoundException.
Unlike NoClassDefFoundError, ClassNotFoundException has to be constructed
with a cause, or it will stupidly set a null cause which can't then be
changed.

This patch also fixes incorrect caching of jclass local references in statics,
which I noticed while fixing the test I'd broken.

Change-Id: I017f4a4e4158554427ccb37b650c985add28980c